name: oci-push

on:
  workflow_run:
    workflows: 
    - oci-builds
    types:
      - completed
  
jobs:
  push:
    name: push
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'pull_request' 
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Download mapt assets
        uses: actions/download-artifact@v4
        with:
          name: mapt
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}

      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push mapt
        run: |
          podman load -i mapt.tar 
          podman push $(cat mapt-image)

        
      